export const utilBuildBaseIssueData = (
    snap: any,
    values: any,
    uploadedUrlList: any[],
    formatted: string,
    userName: string,
    userPhoto: string,
    currentUser: any,
    canvasses: any[]
) => ({
    no: snap?.exists() ? snap.data()?.lastTaskNo : 1,
    description: values.description.trim(),
    assignee: values?.assignee,
    assigneeName: userName,
    assigneePhotoUrl: userPhoto,
    createdBy: currentUser?.displayName,
    createdByUid: currentUser?.uid,
    uiCanvas: canvasses.find((item: any) => item.id == values.uiCanvas)?.label,
    uiCanvasId: values.uiCanvas,
    type: values.type,
    priority: values.priority || "Normal",
    comment: "",
    imageUrl: uploadedUrlList || null,
    createdAt: formatted,
    closedDate: "",
    status: "new",
    api: "",
    apiDescription: "",
    sh: 0,
    eh: 0,
})
